# /etc/ssh/sshd_config.d/99-hobby-hardened.conf
# Default OpenSSH Server Configuration

PermitRootLogin no
PubkeyAuthentication yes
PasswordAuthentication no
KbdInteractiveAuthentication no
X11Forwarding no
MaxAuthTries 4
ClientAliveInterval 300
ClientAliveCountMax 2
