version: '3'

vars:
  VERSION:
    sh: cat VERSION | tr -d '[:space:]'

includes:
  build:   ./tasks/build.yml
  tofu:    ./tasks/tofu.yml
  vm:      ./tasks/vm.yml
  version: ./tasks/version.yml
  test:    ./tasks/test.yml

tasks:
  default:
    cmds:
      - task --list
