version: '3'

tasks:
  build:
    desc: 'Build ze Hobby Linux iso with ze live-build and ze docker'
    cmds:
      - fish scripts/iso-build.fish {{.VERSION}}

  clean:
    desc: 'Clean iso build dir'
    cmds:
      - rm -rf build/
      - rm -f config/binary config/bootstrap config/chroot config/common config/source

  rebuild:
    desc: 'Clean build dir and rebuild the whole iso'
    cmds:
      - task: clean
      - task: build
