version: '3'

tasks:
  default:
    desc: 'Run all tests and linting'
    cmds:
      - task: lint
      - rspec spec

  lint:
    desc: 'Lint the yaml, shell, and fishy files'
    cmds:
      - ruby spec/lint.rb

  spec:
    desc: 'Run test specs (usage: task test:spec -- [unit|integration|e2e])'
    cmds:
      - rspec spec/{{.CLI_ARGS | default "unit"}}
