---
# Only UEFI supported!
efiBootLoader: "grub"
efiBootloaderId: "debian"
installEFIFallback: true

grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiBootMgr: "efibootmgr"
