---
defaultFileSystemType: xfs
defaultPartitionTableType: gpt
createHybridBootloaderLayout: false
luksGeneration: luks1
preCheckEncryption: false

efiSystemPartition: "/boot/efi"
efiSystemPartitionSize: 512M

partitionLayout:
  - name: "boot"
    filesystem: "ext4"
    mountPoint: "/boot"
    size: 1024M
    minSize: 512M
    noEncrypt: true
  - name: "root"
    filesystem: "xfs"
    mountPoint: "/"
    size: 100%

initialSwapChoice: none
