---
modules-search: [ local, "/etc/calamares/modules" ]

instances:
- id:       offline
  module:   packages
  config:   packages.conf
- id:       cleanup
  module:   shellprocess
  config:   shellprocess_cleanup.conf
- id:       bootloader
  module:   shellprocess
  config:   shellprocess_bootloader.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - luksbootkeyfile
  - luksopenswaphookcfg
  - initramfs
  - users
  - hostinfo
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - packages@offline
  - shellprocess@bootloader
  - shellprocess@cleanup
  - umount
- show:
  - finished

branding: hobby

prompt-install: false
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: false
quit-at-end: false
