---
mountOptions:
    default: defaults,noatime
    xfs: defaults,noatime
ssdExtraMountOptions:
    ext4: discard
    jfs: discard
    xfs: discard
    swap: discard
crypttabOptions: luks,discard,initramfs
