---
# Calamares mount module configuration for Hobby Linux
extraMounts:
  - device: proc
    fs: proc
    mountPoint: /proc
  - device: sys
    fs: sysfs
    mountPoint: /sys
  - device: /dev
    mountPoint: /dev
    options: [ bind ]
  - device: tmpfs
    fs: tmpfs
    mountPoint: /run
  - device: /run/udev
    mountPoint: /run/udev
    options: [ bind ]
  - device: /var/lib/iwd
    mountPoint: /tmp/iwd-live
    options: [ bind, ro ]

mountOptions:
  - filesystem: xfs
    options: [ defaults, noatime ]
  - filesystem: default
    options: [ defaults, noatime ]
