---
backend: apt
update_db: true

operations:
  - try_remove:
      - calamares
      - calamares-settings-debian
      - live-boot
      - live-config
      - live-config-systemd
      - live-tools
  - try_install:
      - plasma-welcome
