---
defaultFileSystemType: xfs
defaultPartitionTableType: gpt
createHybridBootloaderLayout: false
luksGeneration: luks2
preCheckEncryption: false

efiSystemPartition: "/boot/efi"
efiSystemPartitionSize: 1024M

partitionLayout:
  - name: "boot"
    filesystem: "ext4"
    mountPoint: "/boot"
    size: 2048M
    minSize: 1024M
    noEncrypt: true
  - name: "root"
    filesystem: "xfs"
    mountPoint: "/"
    size: 100%

initialSwapChoice: none
