---
units:
  - name: NetworkManager
    action: enable
  - name: iwd
    action: enable
  - name: systemd-resolved
    action: enable
  - name: systemd-timesyncd
    action: enable
  - name: ssh
    action: enable
  - name: bluetooth
    action: enable
  - name: fstrim.timer
    action: enable
