---
defaultGroups:
    - adm
    - audio
    - cdrom
    - dip
    - floppy
    - lpadmin
    - netdev
    - plugdev
    - sudo
    - systemd-journal
    - video

autologinGroup:  autologin
doAutologin:     false
sudoersGroup:    sudo
setRootPassword: false
doReusePassword: true

user:
  shell: /usr/bin/fish

hostname:
  template: "hobbylinux"
