---
showSupportUrl:         true
showKnownIssuesUrl:     true
showReleaseNotesUrl:    true
showDonateUrl:          true

requirements:
    requiredStorage:    8.0
    requiredRam:        1.0
    internetCheckUrl:   http://networkcheck.kde.org
    check:
        - storage
        - ram
        - power
        - internet
        - root
    required:
        - storage
        - ram
        - root
